# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager.weiow.com:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/alert-*.yml"
  - "rules/record-*.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets:
      - localhost:9090

  # All nodes
  - job_name: 'nodes'
   # file_sd_configs:
   # - files:                                               
   #   - targets/nodes-*.yaml  
   #   refresh_interval: 2m 
    consul_sd_configs:
    - server: consul.weiow.com:8500
      tags:
        - "nodes"
      refresh_interval: 30s
    relabel_configs:
    - source_labels:
        - __address__
      target_label: app
      regex: .*
      replacement: node-weiow-20230614
      action: replace
    - regex: "app"
      replacement: app_name
      action: labelmap
    - regex: "app"
      action: labeldrop

  - job_name: 'mysqld'
    consul_sd_configs:
    - server: consul.weiow.com:8500
      tags:
        - "mysqld-exporter"
      refresh_interval: 30s

  - job_name: 'nginx'
    consul_sd_configs:
    - server: consul.weiow.com:8500
      tags:
        - "nginx-exporter"
      refresh_interval: 30s

  - job_name: 'tomcat'
    consul_sd_configs:
    - server: consul.weiow.com:8500
      tags:
        - "tomcat-exporter"
      refresh_interval: 30s

  - job_name: 'grafana'
    consul_sd_configs:
    - server: consul.weiow.com:8500
      tags:
        - "grafana"
      refresh_interval: 30s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://weiow.weiyubo.cn    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox.weiow.com:9115'  # The blackbox exporter's real hostname:port.

remote_write:
  - url: http://vm.weiow.com:8480/insert/0/prometheus
remote_read:
  - url: http://vm.weiwo.com:8481/select/0/prometheus
